### ISSUE TITLE
same problem as before

### ISSUE THREAD

**Issue by sscarf** [mastbaum/debugdb#69] opened 2012-06-11 17:04 UTC
i saw that you had fixed the problem of too many tags, but now it is back to doing half of what it was doing...it is now displaying the correct number of tags, but the status shows "none" when it is in fact "gold"

**Comment by mastbaum** [comment] 2012-07-10 13:12
is it still doing this? which board(s)?

**Comment by mastbaum** [comment] 2012-07-11 01:13
duplicate of #68

**Closed as completed by mastbaum** 2012-07-11 01:13 UTC
